Delete-Unnecessary-Files
MichMat/ControlMeasurements pull request #1
Opened 2019-02-05 10:55 UTC by MichMat

2019-02-05 11:18 UTC, LordPike commented
Czemu usunąłeś HomeController.cs? Domyślnie routing jest ustawiony tak, że wchodząc na stronę główną przekierowuje Cię do Home(Controller)/Index(Action). Więc musisz mieć przynajmniej HomeController, w nim akcję Index i powiązany z tą akcją View (Views/Home/Index)

2019-02-05 11:23 UTC, MichMat commented
> Czemu usunąłeś HomeController.cs? Domyślnie routing jest ustawiony tak, że wchodząc na stronę główną przekierowuje Cię do Home(Controller)/Index(Action). Więc musisz mieć przynajmniej HomeController, w nim akcję Index i powiązany z tą akcją View (Views/Home/Index)

2019-02-05 11:25 UTC, CheckmateJ commented
Wiem wiem ze routing tak jest ustawiony, ale chciałem pozniej stworzyc swoj controller i na niego ustawic routing

2019-02-05 11:27 UTC, LordPike commented
> Wiem wiem ze routing tak jest ustawiony, ale chciałem pozniej stworzyc swoj controller i na niego ustawic routing

Ok, jeśli tak chcesz to go zrób i ustaw routing od razu :) Nie możemy zamknąć Pull Requesta, jeśli aplikacja nie działa :)

BTW wydaje mi się, że łatwiej Ci będzie jak zostawisz HomeController i po prostu usuniesz z niego niepotrzebne akcje i odpowiadające im widoki.

2019-02-05 11:43 UTC, MichMat commented
Ok poprawię :)

2019-02-06 09:49 UTC, LordPike requested changes
Widzę, że dodałeś klasę Water, wygląda w porządku, ale moim zdaniem nie należy do zakresu tego Pull Requesta :) Ja bym to zrobił tak:
1) Pull Request "Delete-Unnecessary-Files": usunąć niepotrzebne akcje z HomeControllera (About, Contact) i odpowiadające im Views
2) zrobić nowy PR "Add-water-model": dodać model Water.cs, odpowiednią migrację dla bazy danych
3) zrobić nowy PR "Add-water-logic": dodać odpowiedni widok i kontroler/akcje które będą dodawać/wyświetlać pomiary wody

Dzięki temu każdy PR będzie miał swój osobny zakres i po zmergowaniu każdego będzie wiadomo co zostało dodane.

2019-02-06 09:56 UTC, MichMat commented
Czyli jak tworzylem nowe branche  to do każdej z nich powinienem dodać pull requesta tak?

2019-02-06 10:14 UTC, LordPike commented
> Czyli jak tworzylem nowe branche to do każdej z nich powinienem dodać pull requesta tak?

Tak, dokładnie. Czyli starasz sie zeby dany branch byl osobna funkcjonalnoscia, niezalezna od innnych. Gdy brancha chcesz wciagnac do mastera, to robisz PR :)

2019-02-06 10:36 UTC, LordPike commented
Usuniecie zbednych Actions i Views zrobisz w branchu NewController, zamykam tego PRa  i usunę odpowiadającego mu brancha _DeleteFiles_

2019-02-06 10:36 UTC, closed without merging